### ISSUE TITLE
issue in XENDISCONNECT style

### ISSUE THREAD

**Issue by wirtheim** [cclaerhout/xen_ToggleME#1]
Hi
First of all thanks for the addon its great!!!

I am working with XENDISCONNECT style, 
the + sign is not showing in it, so users cannot see the categories and dont know they can open\close them.

Thanks!!

**Comment by cclaerhout** [comment]
Read the paragraph 3 of the FAQ:
https://xenforo.com/community/resources/toggleme.137/field?field=faq

You can also enable the new pure css mode in the visual properties.
